# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7de6b02a1d59f4439bb834dafdc9b771e06e1eca2b8635edee5d8dbdb7943cdf5d8f6f668f7e133ab4ec535296a6b969a7d09b5f3807272129a463bd1c3c8599

test:
  secret_key_base: 81c0bc2759284295224bed63579ecf9372bd98f17c8961570998e2834097a28d6092c76952592187e29967acb101c536e588f84be4e4f7c5c709713fa69f7221

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
